export default {
    env: {
        browser: true,
        es2021: true,
        node: true,
    },
    extends: ['eslint:recommended', 'plugin:@typescript-eslint/recommended'],
    parser: '@typescript-eslint/parser',
    parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
    },
    plugins: ['@typescript-eslint'],
    rules: {
        indent: ['error', 4],
        'linebreak-style': ['error', 'unix'],
        quotes: ['error', 'single'],
        semi: ['error', 'never'],
        'comma-dangle': ['error', 'never'],
        'no-cond-assign': ['error', 'always'],
        'no-extra-parens': ['error', 'all'],
        'no-unreachable': 'warn',
        'array-callback-return': 'error',
        eqeqeq: 'error',
        'no-else-return': 'error',
        'no-warning-comments': [
            0,
            { terms: ['todo', 'fixme', 'warn'], location: 'start' },
        ],
        'block-spacing': ['error', 'always'],
        'brace-style': 'error',
        'comma-spacing': [2, { before: false, after: true }],
        'comma-style': [2, 'last'],
        'func-names': 'error',
        'key-spacing': ['error', { afterColon: true }],
        'no-multiple-empty-lines': [2, { max: 3, maxEOF: 0, maxBOF: 0 }],
        'no-trailing-spaces': 'warn',
    },
}
